backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "content/images"

collections:
  - name: "post"
    label: "Post"
    folder: "content/blog"
    create: true
    slug: "---"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "content/about.md"
        fields:
          - label: "Title"
            name: "Title"
            widget: "string"
          - label: "Layout"
            name: "layout"
            widget: "select"
            options: ["about", "blog", "contact", "gallery", "page"]
          - label: "Logo"
            name: "logo"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: fals
          - label: "Menu"
            name: "menu"
            widget: "object"
         - label: "Main"
           name: "main"
           widget: "object"
           fields:
             - label: "Weight"
               name: "weight"
               widget: "number"
